select * from EMPLOYEES;
select  FIRST_NAME, LAST_NAME, SALARY from EMPLOYEES where FIRST_NAME='David';
select FIRST_NAME,LAST_NAME, SALARY from EMPLOYEES where FIRST_NAME='David' AND LAST_NAME='Lee';
select * from EMPLOYEES where SALARY>6000;
select EMAIL FROM EMPLOYEES WHERE SALARY<=6000;