select * from employees;
select *from EMPLOYEES ORDER BY SALARY DESC;
SELECT  * FROM EMPLOYEES ORDER BY SALARY ASC;
SELECT EMAIL, SALARY FROM EMPLOYEES ORDER BY SALARY DESC;
SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID<150 ORDER BY FIRST_NAME;
SELECT * FROM EMPLOYEES ORDER BY FIRST_NAME asc , LAST_NAME desc;


