select * from EMPLOYEES;
select * from EMPLOYEES WHERE JOB_ID IN('IT_PROG', 'SA_REP');
SELECT CITY from LOCATIONS where COUNTRY_ID in('IT', 'UK','US');
SELECT * FROM EMPLOYEES WHERE  EMPLOYEE_ID IN('134', '145', '125');
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID IS NULL;
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID IS NOT NULL;