select * FROM EMPLOYEES;
SELECT FIRST_NAME, SALARY FROM EMPLOYEES;
SELECT FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;
SELECT CITY FROM LOCATIONS;
SELECT  COUNTRY_NAME, REGION_ID FROM COUNTRIES;
SELECT JOB_ID, JOB_TITLE FROM JOBS;
SELECT STREET_ADDRESS, POSTAL_CODE FROM LOCATIONS;
SELECT DEPARTMENT_NAME FROM  DEPARTMENTS;
SELECT REGION_NAME FROM REGIONS;

